#ifndef SHADER_DEFINITIONS_GLSL
#define SHADER_DEFINITIONS_GLSL

const uint TOTAL_TEXTURE_TYPE_COUNT = 4;
const uint MAX_MESHES = 8192;
const uint MAX_TEXTURES = MAX_MESHES * TOTAL_TEXTURE_TYPE_COUNT;
const uint MAX_POINT_LIGHTS = 64;
const uint MAX_DIRECTIONAL_LIGHTS = 16;

const uint UNIFORM_BUFFER_BINDING = 0;
const uint STORAGE_BUFFER_BINDING = 1;
const uint DIFFUSE_TEXTURE_BINDING = 2;
const uint SPECULAR_TEXTURE_BINDING = 3;
const uint NORMAL_TEXTURE_BINDING = 4;
const uint HEIGHT_TEXTURE_BINDING = 5;

#endif