#ifndef SHADER_DEFINITIONS
#define SHADER_DEFINITIONS

const uint DIFFUSE_TEXTURE_OFFSET = 0;
const uint SPECULAR_TEXTURE_OFFSET = 1;
const uint NORMAL_MAP_TEXTURE_OFFSET = 3;
const uint HEIGHT_MAP_TEXTURE_OFFSET = 3;
const uint TOTAL_TEXTURE_TYPES_COUNT = 4;

const uint UNIFORM_BUFFER_BINDING = 0;
const uint STORAGE_BUFFER_BINDING = 1;
const uint DIFFUSE_TEXTURE_BINDING = 2;
const uint SPECULAR_TEXTURE_BINDING = 3;
const uint NORMAL_MAP_TEXTURE_BINDING = 4;
const uint HEIGHT_MAP_TEXTURE_BINDING = 5;

const uint MAX_MESHES = 8192;
const uint MAX_TEXTURES = MAX_MESHES * TOTAL_TEXTURE_TYPES_COUNT;
const uint MAX_POINT_LIGHTS = 64;
const uint MAX_DIRECTIONAL_LIGHTS = 16;

const float AMBIENT_STRENGTH = 0.05f;

#endif