//
// Created by Nikolay Kanchevski on 22.09.24.
//

#pragma once

namespace Sierra
{

    enum class Key : uint8
    {
        Unknown,
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        Number0,
        Number1,
        Number2,
        Number3,
        Number4,
        Number5,
        Number6,
        Number7,
        Number8,
        Number9,
        Space,
        Escape,
        Minus,
        Equals,
        Comma,
        Period,
        Apostrophe,
        Semicolon,
        Slash,
        Backslash,
        LeftBracket,
        RightBracket,
        Grave,
        World1,
        World2,
        Enter,
        Backspace,
        Delete,
        Tab,
        CapsLock,
        Insert,
        Section,
        RightArrow,
        LeftArrow,
        DownArrow,
        UpArrow,
        PageUp,
        PageDown,
        Home,
        End,
        ScrollLock,
        NumpadLock,
        PrintScreen,
        Pause,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,
        F16,
        F17,
        F18,
        F19,
        F20,
        F21,
        F22,
        F23,
        F24,
        F25,
        KeypadNumber0,
        KeypadNumber1,
        KeypadNumber2,
        KeypadNumber3,
        KeypadNumber4,
        KeypadNumber5,
        KeypadNumber6,
        KeypadNumber7,
        KeypadNumber8,
        KeypadNumber9,
        KeypadDecimal,
        KeypadDivide,
        KeypadMultiply,
        KeypadSubtract,
        KeypadAdd,
        KeypadEnter,
        KeypadEquals,
        LeftShift,
        RightShift,
        LeftControl,
        RightControl,
        Function,
        Menu,
        LeftAlt,
        RightAlt,
        LeftSystem,
        RightSystem,
        // Windows Keys
        LeftWindows = LeftSystem,
        RightWindows = RightSystem,
        // macOS Keys
        LeftCommand = LeftSystem,
        RightCommand = RightSystem,
        LeftOption = LeftAlt,
        RightOption = RightAlt
    };

    /* --- CONVERSIONS --- */
    [[nodiscard]] SIERRA_API std::string_view GetKeyName(Key key) noexcept;
    [[nodiscard]] SIERRA_API char GetKeyCharacter(Key key) noexcept;

}