name: Pull Request Thanker
run-name: Thank creators of new pull requests

on:
  pull_request:
    types:
      - opened

jobs:
  Thank:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Thank you for your pull request, @${context.payload.pull_request.user.login}!  🎉\n\nYour amazing contribution has us all doing a happy dance! We will review your changes as soon as possible, and in the meantime, feel free to grab a cup of coffee and relax as a reward for your incredible work. Stay awesome and keep coding!`
            });