name: Pull Request Labeler
run-name: Label new pull request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  Label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Label
        uses: actions/labeler@v5.0.0
        with:
          configuration-path: ${{ github.workspace }}/.github/workflows/config/LabelerConfiguration.yaml

